imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $tables: '%tables%'
            $ext_images_path: '%core.root_path%ext/david63/schedulelock/adm/style/images'
        public: true

    david63.schedulelock.listener:
        class: david63\schedulelock\event\listener
        tags:
            - { name: event.listener }

    david63.schedulelock.admin.controller:
        class: david63\schedulelock\controller\admin_controller

    david63.schedulelock.main.controller:
        class: david63\schedulelock\controller\main_controller

    david63.schedulelock.core.functions:
        class: david63\schedulelock\core\functions
